# Generated by Django 4.1.2 on 2022-10-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BizzyCardApp', '0003_carddetails_remove_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetails',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='carddetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='carddetails',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='carddetails',
            name='twitter',
        ),
    ]
