# Generated by Django 4.1.2 on 2022-10-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BizzyCardApp', '0004_remove_carddetails_bio_remove_carddetails_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails_Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('linkedIn', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=130)),
            ],
        ),
        migrations.DeleteModel(
            name='CardDetails',
        ),
    ]
